### ISSUE TITLE
Implementar funcionalidade de abrir conta

### ISSUE THREAD

**Issue by jpedrodsp** [jpedrodsp/aula_github#3]
Criar menu para criação de conta de um cliente.
Com a nova definição, referencie o cliente e adicione uma conta em seu dicionário de contas.

Por favor, faça as devidas validações de dados, e impeça que o usuário crie contas com o mesmo ID.
ID negativos não são problemas, mas sinta-se a vontade para abrir uma issue para alterar isso.

**Comment by jpedrodsp** [comment]
@Wenderson-P - se a conta existe, ele não pode continuar o fluxo do programa. É preciso ter um return aqui, já que o Try/Catch não vai ser chamado.
Você tem duas opções:
1. Fazer um return <error-code>
2. Lançar uma Exception

**Comment by Wenderson-P** [comment]
Alteração feita utilizando um return, caso a conta já exista
